import { NgxUiLoaderConfig } from 'ngx-ui-loader';

export const loaderConfig: NgxUiLoaderConfig = {
  bgsColor: 'rgba(242,240,24,0.93)',
  bgsOpacity: 0.5,
  bgsPosition: 'bottom-right',
  bgsSize: 20,
  bgsType: 'ball-scale-multiple',
  blur: 12,
  delay: 0,
  fastFadeOut: true,
  fgsColor: 'red',
  fgsPosition: 'center-center',
  fgsSize: 50,
  fgsType: 'ball-spin-clockwise',
  gap: 42,
  logoPosition: 'center-center',
  logoSize: 110,
  logoUrl: '',
  masterLoaderId: 'master',
  overlayBorderRadius: '0',
  overlayColor: 'rgba(40, 40, 40, 0.8)',
  pbColor: '#e5ea10',
  pbDirection: 'ltr',
  pbThickness: 6,
  hasProgressBar: true,
  text: '',
  textColor: '#FFFFFF',
  textPosition: 'center-center',
  maxTime: -1,
  minTime: 2000,
};
